### ISSUE TITLE
Addresses with trailing peer IDs get filtered

### ISSUE THREAD

**Issue by anacrolix** [libp2p/go-libp2p-swarm#111]
Address from the peerstore that have trailing peer IDs are filtered out [here](https://github.com/libp2p/go-libp2p-swarm/blob/22f358a2d09ac82ee9ff0774d06010913fa900ad/swarm_dial.go#L292). I don't think this is intentional. It means that arbitrarily added, ("fully-qualified"?) addresses for peers are ignored. I had to work around this [here](https://github.com/anacrolix/go-libp2p-dht-tool/blob/ad36b4be13b82f02a837d46667f3d276430d435c/main.go#L136).

**Comment by Stebalien** [comment]
We usually use https://github.com/libp2p/go-libp2p-peerstore/blob/d2a21b6d4a88bd06c1cd5700b38df4529e556b28/peerinfo.go#L23-L58 for that. We consider everything before the `/p2p` to be the "transport" part, which is the part that goes into the peerstore.

However, we could probably cut off the `/p2p` part inside the peerstore (checking to make sure it matches expected peer.

**Comment by anacrolix** [comment]
Possibly https://github.com/libp2p/go-libp2p-swarm/pull/250 addressed this. I don't know.
