### ISSUE TITLE
Leaking dial errors

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p-swarm#119]
I'm seeing a massive memory leak leaking errors returned by doDial. Not sure _where_ they're getting stashed, maybe in the dialer somewhere?

**Comment by vyzo** [comment]
Maybe introduced by #115? We do aggregate all errors now.

**Comment by vyzo** [comment]
Is there any more detail?

**Comment by vyzo** [comment]
Also are there any stuck goroutines precluding the dial from finishing and accumulating all these errors?
I don't see any place where the errors could be stashed, other than the multierror contraption.

**Comment by vyzo** [comment]
Maybe stuck in a channel though.

**Comment by raulk** [comment]
Yeah, was thinking the same as @vyzo. Could you try with the commit previous to that PR being merged? Not sure if it’s a leak (us unintentionally retaining state) or just a side effect of accumulating all errors from the dial process (especially in the face of addrexplosion).

**Comment by vyzo** [comment]
Can you also check for signs of https://github.com/libp2p/go-libp2p-quic-transport/issues/57? We do happen to have an open bug with stuck dials.

**Comment by Stebalien** [comment]
> Maybe introduced by #115? We do aggregate all errors now.

This has almost certainly made it worse. However, we shouldn't be _storing_ these errors anywhere.

> Can you also check for signs of libp2p/go-libp2p-quic-transport#57? We do happen to have an open bug with stuck dials.

It's probably not that. This error is allocated _after_ all the transport dials finish so a stuck dial would prevent it.

**Comment by raulk** [comment]
It could be the event logging of errors -- the weight of which is now augmented by multierrors. @Stebalien can you generate annotated source for these allocs?

**Comment by Stebalien** [comment]
I don't have the traces but the buildup came from https://github.com/libp2p/go-libp2p-swarm/blob/94a49f124ed974ce57b9ed22c96ddba19a63b077/swarm_dial.go#L259.
