### ISSUE TITLE
Unable to create swarmt with libp2p.NoSecure

### ISSUE THREAD

**Issue by prestonvanloon** [libp2p/go-libp2p-swarm#124]
It seems there is no way to disable security protocol in swarm testing [GenSwarm](https://github.com/libp2p/go-libp2p-swarm/blob/0fc01368da4ae9ce28fc261131494af3eda9aace/testing/testing.go#L62). 

This is making it very difficult or impossible to test hosts with security disabled in unit test due to `got error on dial: failed to negotiate security protocol: protocol not supported `

**Comment by Stebalien** [comment]
Sounds like a reasonable option to add. Want to add one to that package?

**Comment by Stebalien** [comment]
Closing as there doesn't appear to be much interest in this.
