### ISSUE TITLE
Swarm parameters

### ISSUE THREAD

**Issue by JustinDrake** [libp2p/go-libp2p-swarm#14]
These are the swarm parameters I could find:

	- swarm_dial.go
		* dialAttempts = 1
		* concurrentFdDials = 160
		* defaultPerPeerRateLimit = 8
		* DialTimeout = time.Second * 10
		* baseBackoffTime = time.Second * 5
		* maxBackoffTime = time.Minute * 5
		* ConnSetupTimeout = time.Minute * 5
	- swarm.go (yamux)
		* AcceptBacklog = 8192
		* ConnectionWriteTimeout = time.Second * 10
		* KeepAliveInterval = time.Second * 30
		* MaxStreamWindowSize = 1024 * 512

Did I miss any?

**Comment by autonome** [comment]
Looks like a doc question, but likely out of date. Please reopen if there's something actionable still.
