### ISSUE TITLE
Calling DialPeer from DialPeer started goroutine deadlocks.

### ISSUE THREAD

**Issue by Jorropo** [libp2p/go-libp2p-swarm#161]
While implementing [webrtc aside](https://github.com/Jorropo/go-webrtc-aside-transport) I found a deadlock (still finishing properly in a timeout), calling DialPeer on the same peers that was used to instanciate your goroutine (example: calling host.NewStream or host.Connect from the Dial function of a transport (only if peer ID is the same)).

It seems like the first Connect (starting the transport Dial) is the problem, the second one just wait on the channel as expected.
I think transport dial are somehow tested sequentially that mean for Connect to return to the transport would require Dial in the transport to return (here is the deadlocks).

**Comment by Jorropo** [comment]
Issue found, that was on the host, I was at one point beffore doing a Connect with a single address (the one of my transport) and so the host store that in the peerstore, and then future connect don't resolve the dht because routedhost only does if no address are avaible.

Should be solved with peerstore address origin.

**Comment by Jorropo** [comment]
Even with this fixed the bug is still here, while implementing #162 I've found the bug, if a dial already have been started newer address are not reused to start a new dial.

**Comment by Stebalien** [comment]
There's no way to fix this issue inside the swarm itself. Transports need to avoid recursively trying to dial the same peer.

**Comment by Stebalien** [comment]
Nevermind. I'm not sure _how_ to fix this in the swarm itself but we need to find some way to detect this.

**Comment by Stebalien** [comment]
I've re-reported this issue in https://github.com/libp2p/go-libp2p/issues/816 to give a clear description of what's happening.
