### ISSUE TITLE
Hard limit on file descriptors

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p-swarm#165]
The swarm should set a hard limit on new file descriptor consuming connections at 90% of the file descriptor limit. Otherwise, things break terribly.

**Comment by Jorropo** [comment]
I've planned to do it in Quality Transport. The struct returned by `QTransport.Score(...) Score` have an `Fd` field, transport can return the number of `Fd` used to open this connection, if not enough `Fd` are avaible the connection is gonna be put on hold.

**Comment by Stebalien** [comment]
We already track which transports consume file descriptors, that's not the issue. This issue is simply about setting a hard upper limit.

**Comment by marten-seemann** [comment]
Closing in favor of https://github.com/libp2p/go-libp2p/issues/1260.
