### ISSUE TITLE
Race In Dial Limiter

### ISSUE THREAD

**Issue by bonedaddy** [libp2p/go-libp2p-swarm#175]
Running some tests and there appears to be a race in the dialLimiter function. I've attached the logs from `go test` here https://gist.github.com/bonedaddy/139945bc9e190ff43674944f7877eb4c

**Comment by Stebalien** [comment]
That's a race in your test. The read in `github.com/libp2p/go-libp2p-transport-upgrader.(*Upgrader).upgrade()` is reading a global variable (`github.com/libp2p/go-libp2p-core/pnet.ForcePrivateNetwork` that should only be set on `init` (usually via an environment variable). It looks like you're modifying it somewhere.

**Comment by bonedaddy** [comment]
If that's the case the documentation for `go-libp2p-core/pnet` should definitely be updated to indicate that. I read through the code comments and there was nothing discouraging setting this variable outside of init.

Also there has to be a safer way of going about achieving the goals of not setting this value outside of init. Maybe something like a private variable set from within the init function, and a public getting function.

Basically what happened is the same tests, for example in this case a series of basic node tests is repeated twice. Once within a private swarm, and then after those processes are cleaned up and shutdown has finished, the changes made (forcing private network mode) are reverted, and the test is repeated against the node in "public network mode".

While not necessarily a problem, and something that is certainly heavily mitigated by a comment indicating to not modify this variable outside of the init function, the current method of being able to modify this value outside of init seems like a footgun waiting to go off.

**Comment by Stebalien** [comment]
You shouldn't need to set this variable. This variable _forces_ private networks and is designed to be used via the `LIBP2P_FORCE_PNET` environment variable. If you just want to use private networks, you can just construct libp2p with a protector/psk.

Note: You can never set a global variable at runtime without a race as long as something reads that variable.
