### ISSUE TITLE
why not select a match protocol but not just use the last protocol

### ISSUE THREAD

**Issue by hunjixin** [libp2p/go-libp2p-swarm#226]
```go
func (s *Swarm) TransportForDialing(a ma.Multiaddr) transport.Transport {
	protocols := a.Protocols()
	if len(protocols) == 0 {
		return nil
	}

	s.transports.RLock()
	defer s.transports.RUnlock()
	if len(s.transports.m) == 0 {
		log.Error("you have no transports configured")
		return nil
	}

	for _, p := range protocols {
		transport, ok := s.transports.m[p.Code]
		if !ok {
			continue
		}
		if transport.Proxy() {
			return transport
		}
	}

	return s.transports.m[protocols[len(protocols)-1].Code]
}
```

**Comment by aschmahmann** [comment]
@hunjixin is this a question about `transport.Proxy()`?

My understanding is that the idea is if a transport is a proxy transport (e.g. circuit relay) then everything after the proxy is really just information that helps that transport, but cannot be useful for telling us what transport we're using to dial.

For example in a made up `proxy-transport` we could get a multiaddr like `/ip4/1.2.3.4/tcp/1234/p2p/QmRelay/proxy-transport/ip4/9.8.7.6/udp/9876/quic/p2p/QmAlice` that tells us to dial `QmAlice` via `QmRelay` and the `proxy-transport`. As far as our node is concerned we need to use the proxy-transport to connect to `QmRelay` and ask it to proxy us to `QmAlice`, however whether `QmRelay` decides to use the specified transport (QUIC), or any other transport to proxy traffic to `QmAlice` is totally opaque to us.

**Comment by hunjixin** [comment]
@aschmahmann  
local net use the default transport (tcp and ws),  when connect to a node which support protocol(tcp, ws, p2p).  got a err! because local node do not support p2p.  but why not choose  tcp?

**Comment by aschmahmann** [comment]
I'm not sure I understand your question, but:

> because local node do not support p2p

This does not make any sense. Libp2p connections require supporting `/p2p/QmPeer` because without it it's impossible to establish a secure connection. For example, simply connecting to `/ip4/1.2.3.4/tcp/1234/` cannot be secure since there is no way to prevent various attacks such as Man In the Middle. However, by adding the peerID `/p2p/QmPeer` we can cryptographically ensure we are talking to `Peer` and not someone else.

**Comment by hunjixin** [comment]
```
var DefaultTransports = ChainOptions(
	Transport(tcp.NewTCPTransport),
	Transport(ws.New),
)
```
@aschmahmann  so,  local node with transports above cannot connect to remote peer like /ip4/1.2.3.4/tcp/1234/p2p/QmPeer，Is it?

**Comment by aschmahmann** [comment]
Yes, it can connect to those. All libp2p nodes are identified by their peerIDs and being able to process a peerID as part of a multiaddress is mandatory.

**Comment by hunjixin** [comment]
thanks
