### ISSUE TITLE
how to dial self

### ISSUE THREAD

**Issue by bitcard** [libp2p/go-libp2p-swarm#234]
There is such limit in function dialPeer(ctx context.Context, p peer.ID):

if p == s.local {
		log.Event(ctx, "swarmDialSelf", logdial)
		return nil, ErrDialToSelf
}

this mean one node can't dial to self. but http can connect to localhost to get localhost resource, how to dial to self to get self node resource?

**Comment by aarshkshah1992** [comment]
@bitcard 

You can always spin up a new libp2p node/`Host` with a different peerID in your application to dial the other peer.

**Comment by bitcard** [comment]
> @bitcard
> 
> You can always spin up a new libp2p node/`Host` with a different peerID in your application to dial the other peer.
> 
> Please let me if you have any concerns here or I'll close the issue.

thanks for your reply, If create a temp node/host to dial self, the temp node peer info will add to the routing table?

**Comment by aarshkshah1992** [comment]
@bitcard 

You can pass the information about the local node to the temp node during the connect:

```
ctx := context.Background()
local, err := libp2p.New(ctx)
// handler error

temp, err := libp2p.New(ctx)
// handle error

temp.Connect(ctx, peer.AddrInfo{
	ID:    local.ID(),
	Addrs: local.Addrs(),
})
```
