### ISSUE TITLE
Increment 'active' counter in swarm dial worker loop

### ISSUE THREAD

**Issue by schomatis** [libp2p/go-libp2p-swarm#291]
Not sure where it should be incremented but likely around this case:

https://github.com/libp2p/go-libp2p-swarm/blob/87ff7aca8ae058f7fd7bd9ada6bb255fe1b0b3a8/swarm_dial.go#L476-L490

cc @vyzo

**Comment by vyzo** [comment]
is there a reason for that? are we missing something? in short, what's the bug?

**Comment by schomatis** [comment]
I don't have much insight into the code but I think the `active` variable is a counter that tracks processing dials. When we finish with a dial (we get a response from the dial function) we decrement it, but I didn't see any place where the variable was actually incremented.

**Comment by marten-seemann** [comment]
@schomatis @vyzo is there anything we need to do here?

**Comment by vyzo** [comment]
I dont see the bug.

**Comment by vyzo** [comment]
but it must be there.

**Comment by vyzo** [comment]
See #305 -- I was pretty sure this code was there originally!
