### ISSUE TITLE
A question about dialWorkerLoop

### ISSUE THREAD

**Issue by tanqiangyes** [libp2p/go-libp2p-swarm#304]
In swarm_dial.go the dialWorkerLoop function has an active variable inside, when case res := <-resch:, active--, then in this case will determine active==0, but this time active is not certainly less than 0? I don't see active++ or an assignment operation elsewhere. Please help me solve this problem, thank you.

**Comment by tanqiangyes** [comment]
my git submit log is 5155c770

**Comment by marten-seemann** [comment]
@vyzo, can you help out here?

**Comment by vyzo** [comment]
hrm thats the second time we gat this, something is amiss.

**Comment by tanqiangyes** [comment]
> 

Yes, logically, I don't think you are doing anything with this ACTIVE, and many of the conditions about it are not valid. So, is this a logic problem or is there something that is not yet done?

**Comment by vyzo** [comment]
yeah, it's a bug, fixing.

**Comment by tanqiangyes** [comment]
Okay, looking forward to the fix.

**Comment by vyzo** [comment]
#305 fixes the issue.

**Comment by tanqiangyes** [comment]
Can you tell us why you have this logic? Because I tried to fix it, but I don't know why you wrote it that way.

**Comment by vyzo** [comment]
so that we can collect all pending dial results after the request channel has been closed; basically control short-circuits.

**Comment by tanqiangyes** [comment]
Okay, does this bug affect specific businesses?

**Comment by vyzo** [comment]
I don't think so, it's a corner case.

**Comment by tanqiangyes** [comment]
Ok, thanks for the reply. I'm currently learning the libp2p code, and I'm learning a lot, so thanks for your efforts.
