### ISSUE TITLE
Build Error, undefined: transport.TimeoutOpt

### ISSUE THREAD

**Issue by travisperson** [libp2p/go-libp2p-swarm#41]
```bash
$ go get github.com/libp2p/go-libp2p-swarm
# github.com/libp2p/go-libp2p-swarm
../../libp2p/go-libp2p-swarm/swarm_listen.go:23:26: undefined: transport.TimeoutOpt
```

Basically `transport.TimeoutOpt` from `go-libp2p-transport` was removed and `go-libp2p-swarm` still depends on it.

From https://github.com/libp2p/go-libp2p-transport/pull/20
Commit https://github.com/libp2p/go-libp2p-transport/pull/20/commits/1d0d9e50b3e32a0d5e7542e7b60049a91b6a3709
```
remove the TimeoutOpt
Since Go 1.7, net.Dialer has a DialContext, which should be preferred
over setting a fixed timeout duration.
```

https://github.com/libp2p/go-libp2p-swarm/blob/840958c856e197af08848ac074fe43981bbb3dd9/swarm_listen.go#L23

Can this option just be dropped without ill-effects?

**Comment by Stebalien** [comment]
Fix waiting here: https://github.com/libp2p/go-libp2p-swarm/pull/40

**Comment by Stebalien** [comment]
This should now be fixed.
