### ISSUE TITLE
Failures when IPv6 disabled

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p-swarm#42]
On Travis, we appear to be running into a case where to reports that it's listening on a socket on  `[::]:$port` while the OS doesn't report any IPv6 enabled interfaces. This shouldn't happen.

**Comment by anacrolix** [comment]
@Stebalien This is [coming up](https://circleci.com/gh/libp2p/go-libp2p-swarm/tree/master) now with CircleCI.

**Comment by Stebalien** [comment]
Lovely.

**Comment by anacrolix** [comment]
I think I fixed this in #105. Alternatively it would have been possible to enable IPv6 on CircleCI by using machine like [this](https://github.com/libp2p/go-libp2p-quic-transport/pull/47/commits/2839b7c78fad74897085024a10d26f899f14451e).
