### ISSUE TITLE
Stop taking a context in the constructor.

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p-swarm#59]
1. It's redundant with the `Close` method.
2. This isn't really the appropriate use for a context as one isn't supposed to hang onto them (that's what `io.Closer`s are for).
3. While the basic Host also takes a context, it completely ignores it.

Thoughts @whyrusleeping? This came up when trying to actually document the libp2p constructors.

**Comment by Stebalien** [comment]
https://golang.org/pkg/context/:
> Do not store Contexts inside a struct type; instead, pass a Context
explicitly to each function that needs it.

**Comment by whyrusleeping** [comment]
Yeah, I think we can probably remove the contexts. They were initially for tracking background pocesses, but I think governing their life with the `Close` method is more correct.

**Comment by Stebalien** [comment]
TODO:

* [ ] go-libp2p-swarm
* [ ] go-libp2p-kad-dht
* [ ] go-libp2p/p2p/host/basic
* [ ] go-libp2p-circuit
* [ ] go-floodsub

(and probably more...)

For now, I'm just going to fix this the other way and actually use the contexts.

**Comment by vyzo** [comment]
Some of these use the context for background purposes, as was intended.

**Comment by Stebalien** [comment]
I agree. However, IMO, those should be constructed internally, not passed in. Contexts were designed to govern the lifetime of requests, not services/processes. For example, they provide no way to wait for children to finish/exit. This means we *can't* rely on them to shut down services as we have no way to know when it's safe to exit the program.

The other issue in this case we're providing *two* ways to close services and, in many cases, it looks like the only way to fully shutdown a service is to *both* cancel the context and call `Close`. At the very least, we need to fix that.

**Comment by anacrolix** [comment]
I'm applying this to swarm and DHT in some places.

**Comment by raulk** [comment]
@anacrolix note that you may be underestimating the work here. This will better accomplished as part of the host/service refactor (which forces us to model service lifecycles), rather than in isolation. It's not clear to me where, who and how the `Close()` methods are to be called.

**Comment by marten-seemann** [comment]
This was fixed a while ago.
