### ISSUE TITLE
Add a `Dial: false` context option.

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p-swarm#60]
Sometimes, services want to open a stream to a peer *iff* we already have a connection to them. Currently, they do this by checking for an open connection and, if it turns out we have one, opening a stream. However, that's quite racy.

Proposal: Allow adding `Dial: false` to the context to avoid opening any new connections. This is similar to my `Offline` context variable proposal except that this one really is just a hint. Nothing *bad* will happen if we happen to dial anyways, we just want to inform the swarm that we don't want to put too much effort into opening this stream.

Other parameters:

* `PeerRouting: false`? Could be useful when we don't want to go looking for more addresses in the DHT.
* `AddrFilter: func`. Filters out addrs we don't want to use when completing the request. Probably *really* complicated and something we can look at way down the road.

**Comment by Kubuxu** [comment]
It seems that we want to add more and more dial options. Another option would be creating method: `DialOpts(peerid, opts...)` on the `Network` interface (I think it is that interface).

What do you think?

**Comment by Stebalien** [comment]
Well, the `Dial: false` option would actually have to be an option on `NewStream`. However, the more general issue is that we'll often need to thread these options through methods. For example, `NewStream` will have to forward the dial options. That's why I suggested adding them to the context.

**Comment by whyrusleeping** [comment]
Also having a 'prefer relay' option would be great, plus the ability to specify which addresses to use (strictly or as a suggestion)

**Comment by whyrusleeping** [comment]
Actually, If we just add the ability to specify specific addresses to try first, that would satisfy needs.

**Comment by anacrolix** [comment]
Per https://github.com/libp2p/go-libp2p/issues/526, a configuration struct might be preferable. There's also an existing pattern for dial configs in the Go standard library.

**Comment by Stebalien** [comment]
This has been fixed.
