### ISSUE TITLE
Proposal: replace ConnNotify with PeerNotify

### ISSUE THREAD

**Issue by whyrusleeping** [libp2p/go-libp2p-swarm#61]
Users of libp2p shouldnt care about individual connections. They care about peers, exposing new connection notifications (and the refcounting that is sometimes required there) complicates things immensely. We should to that tracking here, and only expose when a peer is connected or disconnected from us (regardless of which connections are made)

**Comment by Stebalien** [comment]
Yeah, the events are `PeerConnected` and `PeerDisconnected`.

**Comment by marten-seemann** [comment]
We have these events now, as event bus notifications.
