### ISSUE TITLE
Dial timeouts not being respected?

### ISSUE THREAD

**Issue by whyrusleeping** [libp2p/go-libp2p-swarm#67]
It appears that we are no longer setting dial timeouts (either that, or i'm missing where thats supposed to happen). We used to have DialTimeouts set (globally) in go-libp2p-conn, but it appears that that package has been deprecated in the refactor (is that right @Stebalien ?)

**Comment by Stebalien** [comment]
There's a maximum `DialTimeout` of 60 seconds set in the swarm package. It's applied to the context in `doDial`.

**Comment by Stebalien** [comment]
I've noted this in the release notes. Also, https://github.com/libp2p/go-libp2p-transport/issues/32
