### ISSUE TITLE
Work towards eliminating Conn and Stream types

### ISSUE THREAD

**Issue by whyrusleeping** [libp2p/go-libp2p-swarm#7]
The Conn and Stream types in this package are mostly redundant shims. It would be very nice if we could eliminate them entirely.

If we collapse a bit more of the libp2p-net interfaces down into libp2p/go-peerstream we should be able to just use streams and conns from that package in place of the current swarm stream/conn

**Comment by whyrusleeping** [comment]
Looking at doing this a bit more in depth. I think the *right* path forward will be to sink the go-libp2p-net interfaces down into go-peerstream and make `go-libp2p-net.Stream.Conn()` just return an `interface{}` or a basic `net.Conn`, but having it return the 'top level' interface makes the stackability difficult. It could also be reasonably to keep it the way it is, since we'll already have that type down in go-peerstream, it just might make lower level composability more annoying.

The core question here is what input and output interfaces should go-peerstream handle? right now it takes in a `transport.Conn` and outputs an *almost* `swam.Conn`

**Comment by Stebalien** [comment]
@marten-seemann we should consider revisiting this issue. Thoughts?

**Comment by marten-seemann** [comment]
@Stebalien: I like that idea. There are just too many conns and streams around in libp2p.
I'll start looking into that when the MultiStreamConn-PR is merged.

**Comment by Stebalien** [comment]
The refactor has taken care of this. We now have libp2p-net conns (implemented in this package) and libp2p-transport conns (implemented by transports).
