### ISSUE TITLE
Is there an upper limit on the number of connections a peer can have ?

### ISSUE THREAD

**Issue by aarshkshah1992** [libp2p/go-libp2p-swarm#91]
We use DHT random walks to discover more peers.However, given that the number of peers discovered by a random walk is effectively unbounded, this means that a peer can have a huge number of connections open. Shouldn't there be an upper limit on how many connections a peer can have open at given point of time ?

**Comment by raulk** [comment]
Yes, the [Connection Manager](https://github.com/libp2p/go-libp2p-connmgr) takes care of keeping the connection count within sensible bounds. It does so by weighing the value of peers based on "tags". This is a simplistic model and there is a new approach in the works: https://github.com/libp2p/go-libp2p/issues/475

**Comment by Stebalien** [comment]
Note: If by "random dht walk" you mean "try to find a random key", each search should only connect to (about) `log(size_of_network)` nodes. The walk will terminate when you get to the closest (in terms of xor key distance) node.

**Comment by marten-seemann** [comment]
There's nothing actionable here. Closing.
