### ISSUE TITLE
swarm connections are not always established

### ISSUE THREAD

**Issue by Raisongran** [libp2p/go-libp2p-swarm#92]
I found that when establishing a connection between two devices with a command

```
$ ipfs swarm connect /p2p-circuit/ipfs/QmA
connect QmA success
```

in some cases, the list of active peers `ipfs swarm peers` remains the same. So it works as in the case of QmA -> QmB and in the case of QmA <- QmB. Also note that the message about successful connection appears without delay. Since the connection is not established, I can not use pubsub. Repeating command execution also succeeds, but in fact nothing happens.

When both ipfs daemon are rebooted and I try to connect to one of the devices again, it is actually connects with a little delay and the `/ipfs/QmBridge/p2p-circuit/ipfs/QmA` format entry appears in `ipfs swarm peers` for some time, after which the connection is terminated and this the problem arises again. With a small probability, I can still make connections without restarting ipfs daemon, but this usually does not happen.

Both ipfs daemons are running on

```
go-ipfs version: 0.4.18-
Repo version: 7
System version: amd64/linux
Golang version: go1.11.1
```

**Comment by Stebalien** [comment]
Just to make sure, you're saying that running `ipfs swarm peers | grep QmB` on QmA *fails* after `ipfs swarm connect /p2p-circuit/ipfs/QmA` succeeds? Does this happen *without* `p2p-circuit`?

@vyzo can you look into this?

**Comment by vyzo** [comment]
Note that we have deprecated the unspecific relay address dialing; still, it should not claim success without successfully dialing.

**Comment by Raisongran** [comment]
Today I noticed another oddity. Provided that:
Node A:
```
$ ipfs swarm peers | grep QmB
/ip4/10.8.8.31/tcp/56450/ipfs/QmB
```
Node B:
```
ipfs swarm peers | grep QmA
/ip4/10.8.8.31/tcp/4001/ipfs/QmA
/ipfs/QmA/p2p-circuit/ipfs/QmX
```

When I executed the commands listed below, everything worked exclusively in one direction (I could not do the same with `QmA -> QmB`). After a while, communication became impossible at all.
Node A:
```
$ ipfs pubsub sub someChannel
1
```
(Node B sent '1')

Node B:
`$ ipfs pubsub pub SomeChannel 1`

At the same time, on each node, the ping command was executed normally (for `QmA -> QmB` and `QmA <- QmB)`. After I rebooted daemon of node B, communication began to work again in normal mode.

**Comment by vyzo** [comment]
I haven't been able to reproduce yet. Is this something that happens consistently?

**Comment by Raisongran** [comment]
> I haven't been able to reproduce yet.

Me too. Yes, it happened consistently, as I described. If I come across something like this, I will report here.

**Comment by marten-seemann** [comment]
Closing, as we haven't seen this for more than 3 years.
